version: "3.7"

services:
    app:
        image: "sicei-${GIT_BRANCH}:1.0.0-${BUILD_NUMBER}"
        build:
            args:
                user: testusr
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: test-app-sicei-1.0.0-${BUILD_NUMBER}
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - test-network

    web:
        image: nginx:1.19.4
        container_name: test-nginx-sicei-1.0.0-${BUILD_NUMBER}
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - test-network
networks:
    test-network:
        driver: bridge
